### ISSUE TITLE
Almost there, just TTS with alltalk_tts left!

### ISSUE THREAD

**Issue by CodeShadower** [semperai/amica#140]
Hello guys! First of all, thank you for this integrated software which has really been thought trough and which is so modular! GREAT JOB!!! :smiley: 

**Context**

- Ubuntu 24.04.01 LTS
- Python 3.12.3

**Goal**
I try to achieve a complete local installation with:

- **OK** ChatBot: llama.cpp (however with the original github instructions, because Amica's instructions are mostly outdated) 
- **OK** STT: whisper.cpp (however with the original github instructions, because Amica's instructions are mostly outdated)
- **WIP** TTS: alltalk_tts
 
**Symptoms**

a) Basically, lipsync.ts has issues processing the stream properly:

![2024-11-09_14-18 Amica error message when getting audio back](https://github.com/user-attachments/assets/575920e6-ed3a-4101-8f22-4e9c2cec8f67)

![2024-11-09_16-35 Browser debugging tools](https://github.com/user-attachments/assets/1d437d47-b082-4dca-89c1-0c3c520dcd4e)

b) all the user's input text/voice lands in a single chat bubble instead of separate bubbles for the user and Amica's answers are missing:

![2024-11-09_14-17 Amica no messages written and played back](https://github.com/user-attachments/assets/30d64b26-afec-404e-b6a8-fc86e59f76eb)

**Debugging so far with alltalk_tts**

1. **KO**: alltalk_tts installation according to [Amica instructions](https://docs.heyamica.com/connecting-speech-options-tts/using-alltalk).
Result: Errors at launch, PortAudio not recognized though installed, Amica input is sent to TTS, but not spoken.

![2024-11-09_15-09 AMica Specific alltalk_tts conda installation](https://github.com/user-attachments/assets/93e7b3e4-e2fb-4e26-8871-09d507ed2bc7)

2. **KO**: alltalk_tts v1.9c (main) installation according to alltalk_tts author has the same issues:

![2024-11-09_15-38 alltalk_tts_v1 Receives input but no output sound](https://github.com/user-attachments/assets/38f9f775-c786-44d4-a9a1-d76f7aeef424)

3.  **WIP**: However, after [debugging with the alltalk_tts author directly](https://github.com/erew123/alltalk_tts/issues/400), he updated [alltalk_tts v2 beta](https://github.com/erew123/alltalk_tts/tree/alltalkbeta) and made a [specific wiki page for Amica](https://github.com/erew123/alltalk_tts/wiki/Amica-with-AllTalk-V2). The result is now, that no more errors appear after alltalk_tts v2 beta launch, Amica's output is processed by the TTS in text and audio form:

![2024-11-09_13-57 alltalk_tts_v2_beta output](https://github.com/user-attachments/assets/55cf122f-ddde-48e1-b08d-e04223fa181c)

I tinkered a bit with alltalk_tts [API global settings](http://127.0.0.1:7852/?__theme=dark), but with no success:

![2024-11-09_15-18 alltalk_tts API Settings tweaks](https://github.com/user-attachments/assets/77a4b1a3-2bb6-4944-8a25-e1aeebced5bb)

That's about how far I can go with my skills. Could you please have a look and tell me what I'm missing?

**Comment by CodeShadower** [comment]
Hey @erew123 , you totally rock!!! That's a fantastic job! Thank you very much! :smiley:

**Comment by slowsynapse** [comment]
This is wonderful, we are reviewing this now. Thanks so much @CodeShadower @erew123

**Comment by slowsynapse** [comment]
Merged. Thanks so much guys!
