### ISSUE TITLE
Implement support for memgpt server

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#16]
While this is still early, it would be really cool to support memgpt websocket server as a chatbot backend

https://github.com/cpacker/MemGPT/

**Comment by slowsynapse** [comment]
Arbius has a $200 AIUS bounty for this issue!

Brief: Fix/Complete Issue, with explanation of what was done to achieve this.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.
