### ISSUE TITLE
getusermedia

### ISSUE THREAD

**Issue by cake2** [semperai/amica#17]
How do you use this in a headless server? The latest browsers (firefox/chrome) want a https connection. So instead of localhost, I just enter IP of server on the LAN. Where to install the certificates at?

vad error {"message":"getUserMedia is not implemented in this browser"}

This is nice though!

**Comment by kasumi-1** [comment]
Hey,

We should probably put together guide for how to do this, but check out this thread https://www.reddit.com/r/homelab/comments/uaqy88/ssl_certificates_for_local_network_home_domain/ has some script that should work. Basically, you will want to have your server configured to use the self signed cert, and on your device import the cert.

**Comment by morphles** [comment]
@cake2 for me I did not want to bother with that, I have my phone on my home vpn via NAS, and just connect to my main machine. Now of course there is that thingie that it wants https, but with chrome (which I genearlly don't use) there is option to treat insecure origins as secure (for specific hosts), so I just set that to my machines lan ip and it works with no certs. And I can chat hands free on my lunch walk or what no :)

**Comment by slowsynapse** [comment]
Arbius has a $200 AIUS bounty for this issue!

Brief: Fix/Complete Issue, add function calling from Ollama, but do this in a way that function calling can be extended to using other things other than Ollama in the future.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.
