### ISSUE TITLE
Support newer node versions

### ISSUE THREAD

**Issue by Vuizur** [semperai/amica#19]
Thanks a lot for developing this project! The result is pretty impressive.

Currently, the package.json only specifies that Node 18 is supported. It would be nice if newer Nodes could be used. I just tried it with Node 21 (the "Echo" Chat mode), and it seemed to work.

**Comment by kasumi-1** [comment]
Thanks for letting me know! Fixed here 4bb90386d574aa23b5ddea31de96e7ca6da05d85

**Comment by Vuizur** [comment]
Thanks!
