### ISSUE TITLE
Feature request: KoboldAI API support

### ISSUE THREAD

**Issue by henk717** [semperai/amica#2]
In the different implementations you missed KoboldAI's API.
Its interactive documentation can be found on our sample instance : https://koboldai-koboldcpp-tiefighter.hf.space/api

Python based example can be found here : https://github.com/henk717/KoboldAI/blob/united/api_example.py

**Comment by kasumi-1** [comment]
Thank you, I'll add soon!

(I thought many people used the openai wrapper for kobold that's why I didn't add already!)

**Comment by kasumi-1** [comment]
Hi, me and @PatrickLearn implemented this. It uses just the streaming endpoint in extras, and allows you to set the url root for kobold.
