### ISSUE TITLE
Special characters - other languages 

### ISSUE THREAD

**Issue by mihau12** [semperai/amica#21]
Hey! Very interesting work! Thanks! 

Could you tell me how can I add support for other languages? It doesn't display polish special characters during conversation which leads to wrong pronunciation by TTS model. 

Input works but output by the model shows truncated text without special characters

**Comment by kasumi-1** [comment]
Woops, I wrote reply and it disappeared. 

I just removed the code (b94d1b58bcacb36992c33f7fa98fd3f6d8f1b392) that removed non-ascii characters. Some times chatbot reply with something that is unpronounceable, but this is clearly wrong hack :) 

There are some old commits which removed i18n support from the branch this pull from: 

* 0e3a00e2a64e9da4bb68985124cc574955d2e4a3
* 7436b656a6ae578b9ce80c8787fc841d7c40df11

I think having language selector for interface would be great, though it is a lot of work to translate everything.
