### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by Anon2578** [semperai/amica#23]
We should add function calling since the model uses ollama can add ollama functions to be able to have amica search the web, extract info from news, Turn on and off lights etc.

**Comment by kasumi-1** [comment]
I split off some code into processResponse which should make it easier to add more parsing logic into this, but haven't gotten that far yet.

**Comment by slowsynapse** [comment]
Arbius has a $200 AIUS bounty for this issue!

Brief: Fix/Complete Issue, add function calling from Ollama, but do this in a way that function calling can be extended to using other things other than Ollama in the future.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.
