### ISSUE TITLE
Use Mixamo animations?

### ISSUE THREAD

**Issue by morphles** [semperai/amica#25]
For almost a week now I was looking where I could download free vrma animations, and... Couldn't really find it. Found some guides how to convert some other types (mixamo in particular) using say blender. Still haven't gotten to it, but searching again I see that seems underlying library already support mixamo animations: https://github.com/josephrocca/ChatVRM-js and it's even in repo https://github.com/semperai/amica/blob/ff7bb037cabc981600140c8ba89025f3b839d913/src/lib/VRMAnimation/loadMixamoAnimation.ts#L13 but not exposed in any way. As mixamo is free and provides loads of anims, I think it would be of great benefit to allow loading those animations via interface or maybe adding to server dir (like I did with bunch of vrm's) to select from menu. I'm so bummed out by idle only animation, that might look into it myself come weekend or so.

**Comment by morphles** [comment]
Did a quick and dirty code tweas, it loads :) Will create PR later.

**Comment by morphles** [comment]
Should be good now.

**Comment by kasumi-1** [comment]
This is great!

I started on /share and /import/[sqid] pages for making&sharing characters, maybe these come with a default animation? Not sure how to best do this. 

I think the fbx files too big to import all of them into repo, but in working on the character creator I set up a s3 compatible bucket for big files.. maybe I can just download all mixamo files and provide the urls? Or a script to allow users to download them to their own computers, so they aren't dependent on internet at all.

**Comment by morphles** [comment]
Are you sure that there would be no legal trouble from rehosting them? miximo is adobe after all... Imo people can just be pointed where to download and they can make selection :)

**Comment by kasumi-1** [comment]
I think it's ok. If adobe lawyers message me that this is in violation then I guess they disagree. As far as I understand they just dont want you reselling asset packs using their stuff, since this is a "Game" making it available for "Players" should be fine. 

But yes, we should/could point people towards it as well. There's some customization options people may want for these. Have to think more on it.

**Comment by morphles** [comment]
I think issue can be closed no?
