### ISSUE TITLE
Model on online demo

### ISSUE THREAD

**Issue by Aspie96** [semperai/amica#3]
Hi.

It's not clear to me what model is being used in the online demo, but it appears to be LLaMA 2, correct me if I am wrong.

If this is so, may I suggest considering switching to something like mistral-openorca, zephyr, dolphin2.2.1-mistral, openhermes2.5-mistral, openchat or neural-chat?

Unlike LLaMA (2), which has a proprietary license by Meta, these models are all under an open source license and are based on Mistral, which is under the Apache 2.0 license and some of them may even outperform LLaMA 2.

**Comment by kasumi-1** [comment]
Hi! The demo is using OpenChat 3.5 by Alignment Lab, which is Mistral based.

**Comment by Aspie96** [comment]
Thank you, @kasumi-1, my bad. I will close the issue.

Is this documented anywhere?

The reason I thought it was LLaMA 2 is that it appears as the suggested default model if you open the Ollama settings:

![image](https://github.com/semperai/amica/assets/13873909/6820a396-c5de-4cce-96b9-b7dbd75f3ab5)

**Comment by kasumi-1** [comment]
I don't think it is documented, just from launch announcement. I'll add to the faq on heyamica.com - thank you

**Comment by Aspie96** [comment]
Thank you a lot!

Please, consider updating Ollama default settings for consistency.
