### ISSUE TITLE
Potential errors in the system prompt

### ISSUE THREAD

**Issue by Aspie96** [semperai/amica#4]
First of all, this is a cool project, thank you for making it open source!

The issue is about the  `system_prompt` configuration variable: https://github.com/semperai/amica/blob/438c09ccd42b7f9afc8363afb14b00bc2e94731f/src/utils/config.ts#L37C112-L37C112

The default system prompt is a bit weird at times. I am not sending a patch because, while the changes are trivial, I am not certain of the intention of the authors.

> There are five types of emotions: 'neutral' which indicates **normal**, 'happy' which indicates joy, 'angry' which indicates anger, 'sad' which indicates sadness, and 'relaxed' which indicates calmness.

While "normal" [can](https://www.oxfordlearnersdictionaries.com/definition/american_english/normal_2) be used as a noun, I believe "normality" would feel more natural in this context.

The prompt then uses the word "conversation" to refer to individual messages. "Message" would be more natural.

> Please do not use polite language.

This is counterintuitive. Is there any reason for asking the model to *not* use polite language?

**Comment by kasumi-1** [comment]
Thanks!

Good points, am open to PR if you like.

> This is counterintuitive. Is there any reason for asking the model to not use polite language?

I do not remember, but guess is to try to reduce the overly polite assistant vibe and speak more like normal person.
