### ISSUE TITLE
Basic charater save/load

### ISSUE THREAD

**Issue by morphles** [semperai/amica#42]
I know there is more advanced, char card issue already. Might even look into that. But this is for very basic load/save. I actually have it almost done, have select/load working. Still have to sort out saving, and Sqlite DB initialization. Still I hope to do a PR in coming couple days. So this is placeholder issue for that, also as this one is more involved than my previous changes I expect some comment's exp with regards to translations, but hopefully you'll just be able to edit that stuff simply.

**Comment by slowsynapse** [comment]
Arbius has a $100 AIUS bounty for this issue!

Brief: Fix/Complete Issue, with interface to see and load saved character.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by slowsynapse** [comment]
Bounty is closed—alternative settlement.
