### ISSUE TITLE
support piper tts

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#49]
https://github.com/rhasspy/piper

**Comment by kasumi-1** [comment]
It may make sense to fork piper and add a server build using httplib similar to whisper.cpp server

**Comment by slowsynapse** [comment]
Arbius has a $100 AIUS bounty for this issue!

Brief: Fix/Complete Issue.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by flukexp** [comment]
I claim this bounty

**Comment by flukexp** [comment]
[#85 ](https://github.com/semperai/amica/pull/85)

**Comment by slowsynapse** [comment]
Please put your Ethereum address here.

**Comment by slowsynapse** [comment]
> It may make sense to fork piper and add a server build using httplib similar to whisper.cpp server

Issue kept open, since Piper support added, but server is on another repo.

**Comment by flukexp** [comment]
> Please put your Ethereum address here.

0xD44248b6Ab4B6580cd982A80D4B26dC7058264f2

**Comment by slowsynapse** [comment]
Bounty sent rewards with #54  : [https://etherscan.io/tx/0xb50e3b438db231e3de48ad674af3dcefbcde8090cf1461333c290362ecd2606b?__cf_chl_tk=iEk9B0QAmaj2zaBd8r_MGtGQjHgl4mOm_AwchPgWodo-1712532013-0.0.1.1-1514](https://etherscan.io/tx/0xb50e3b438db231e3de48ad674af3dcefbcde8090cf1461333c290362ecd2606b?__cf_chl_tk=iEk9B0QAmaj2zaBd8r_MGtGQjHgl4mOm_AwchPgWodo-1712532013-0.0.1.1-1514)
