### ISSUE TITLE
[tauri] bundle llama.cpp, whisper.cpp, and tts for all-in-one easy setup/install

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#50]
Would be cool if users could just download an installer, download model when it loads, and start using amica without requiring additional setup. 

requires a model downloading solution and #49

**Comment by slowsynapse** [comment]
Arbius has a $500 AIUS bounty for this issue!

Brief: Fix/Complete Issue, with an explanation of what was done to achieve this. All-in-one installs all the prerequisites for running Amica locally without setup on first run.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.
