### ISSUE TITLE
[tauri] support arm build for orange pi and rpi

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#51]

**Comment by slowsynapse** [comment]
Arbius has a $300 AIUS bounty for this issue!

Brief: Fix/Complete Issue, with explanation of what was done to achieve this.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by Wilaz** [comment]
Do you want ARM64 or 32 or both?

**Comment by majorlegendx** [comment]
Both would be nice. : )

**Comment by slowsynapse** [comment]
Both would be nice : )
