### ISSUE TITLE
refactor share page to be a modal component

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#52]
The separate page for /share is unnecessary and causes conversation state to be lost.

**Comment by agrim0312** [comment]
hey @kasumi-1 can i work on this

**Comment by kasumi-1** [comment]
@agrim0312 sure thing!

**Comment by agrim0312** [comment]
@kasumi-1 are you using any UI library or i need to build it from scratch using divs??

**Comment by kasumi-1** [comment]
tailwind

**Comment by agrim0312** [comment]
@kasumi-1 please check the PR and please guide me if any changes required as i am new to open source.
