### ISSUE TITLE
[tauri] add splashscreen for initial load

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#54]
https://tauri.app/v1/guides/features/splashscreen

**Comment by oranjan** [comment]
Hi , can I work on this ?

**Comment by kasumi-1** [comment]
@oranjan of course :)

**Comment by oranjan** [comment]
Hi, can you explain 
<img width="126" alt="Screenshot 2023-12-16 161901" src="https://github.com/semperai/amica/assets/109731736/d74c3a09-a05e-4378-b29a-6bc64506d9dc">
 this : according to the doc provided  **distDir** is the folder where we need to make splashscreen.html ,however    in tauri.config.json ` "distDir": "../out"` is written but there is no file/folder named **out**
<img width="130" alt="Screenshot 2023-12-16 161930" src="https://github.com/semperai/amica/assets/109731736/008c7b02-1ac6-4f3c-aa96-b2da4fa9bd6a">

**Comment by kasumi-1** [comment]
@oranjan this is generated by `npm run export`, or when doing `npm run tauri build`

**Comment by slowsynapse** [comment]
Arbius has a $75 AIUS bounty for this issue!

Brief: Fix/Complete Issue.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by flukexp** [comment]
I claim this bounty

**Comment by flukexp** [comment]
[#87](https://github.com/semperai/amica/pull/87)
0xD44248b6Ab4B6580cd982A80D4B26dC7058264f2

**Comment by slowsynapse** [comment]
Thank you. Merged.

**Comment by slowsynapse** [comment]
Bounty sent rewards with #49 : [https://etherscan.io/tx/0xb50e3b438db231e3de48ad674af3dcefbcde8090cf1461333c290362ecd2606b?__cf_chl_tk=iEk9B0QAmaj2zaBd8r_MGtGQjHgl4mOm_AwchPgWodo-1712532013-0.0.1.1-1514](https://etherscan.io/tx/0xb50e3b438db231e3de48ad674af3dcefbcde8090cf1461333c290362ecd2606b?__cf_chl_tk=iEk9B0QAmaj2zaBd8r_MGtGQjHgl4mOm_AwchPgWodo-1712532013-0.0.1.1-1514)
