### ISSUE TITLE
Wake word?

### ISSUE THREAD

**Issue by dillfrescott** [semperai/amica#55]
This would be great to be able to set a wake word so if you are talking to someone else Amica doesnt get confused

**Comment by pyrater** [comment]
+1

**Comment by slowsynapse** [comment]
Arbius has a $100 AIUS bounty for this issue!

Brief: Add wake word as an optional setting. STT process does not trigger unless Wake word is seen in input.


Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by danyyil-pelekhatyi** [comment]
I claim this bounty

**Comment by danyyil-pelekhatyi** [comment]
https://github.com/semperai/amica/pull/82

**Comment by slowsynapse** [comment]
Bounty is closed—alternative settlement.
