### ISSUE TITLE
Autotranslate - Google Translate / Deepl API?

### ISSUE THREAD

**Issue by ostov-larion** [semperai/amica#59]
Most models have poor generation quality in languages other than English. So much so that intermediate translation between generations (Human input ⇒ English, AI output ⇒ User Language) will be a better approach. Can we hope to add this feature?

**Comment by kasumi-1** [comment]
I like the idea.

One of the things I've been using Amica for is a language tutor. It may be nice to show both pre-translated and post-translated text.

I think this belongs in some sort of plugin like described in #40 - I'll leave this open
