### ISSUE TITLE
"getUserMedia is not implemented in this browser": v0.2.0 for MacOS

### ISSUE THREAD

**Issue by andyccliao** [semperai/amica#64]
For the MacOS release (.dmg) v0.2.0, the microphone cannot be used, and there are many errors saying 'vad error {"message":"getUserMedia is not implemented in this browser"}'.

**Comment by kasumi-1** [comment]
Confirmed, looking at a fix now

**Comment by kasumi-1** [comment]
I attempted a fix here, seems to work on macOS 13.6 

https://github.com/semperai/amica/releases/tag/app-v0.2.1

Please feel free to re-open if this doesn't work..

Thanks for the report, much appreciated. I tested using a local build initially but not the one from GitHub, stupid me :)
