### ISSUE TITLE
build docker image and publish it.

### ISSUE THREAD

**Issue by Yvonne-Aizawa** [semperai/amica#65]
Hello,
In response to the docker file i made. #61

Would it be possible to publish the docker image ter docker hub or github packages?

o eith

I could write a GitHub action that automatically builds the docker image and puts it on GitHub packages. i think this could be possible with docker hub too.

It could be possible to write it as such that it runs when there is a commit (for a beta image) and with every release (every major update)

**Comment by kasumi-1** [comment]
That would be great.

Comparing the two registries:

* github container service has max size of 500mb for free accounts
* docker hub doesn't seem to have a limit (but more than 10 or 20gb may have issues)

 For actions, I have a `release` branch I push to for generating a release. 
 
 
 I also wonder if docker should be performing tauri build & run. Wdyt?

**Comment by slowsynapse** [comment]
Arbius has a $50 AIUS bounty for this issue!

Brief: Fix/Complete Issue.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.
