### ISSUE TITLE
hide window.ai in tauri build

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#68]
since it relies on a browser extension, there is no reason to show it in interface.

**Comment by slowsynapse** [comment]
Arbius has a $120 AIUS bounty for this issue!

Brief: Complete/fix issue.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by Wilaz** [comment]
I claim this bounty

**Comment by Wilaz** [comment]
> Arbius has a $120 AIUS bounty for this issue!
> 
> Brief: Complete/fix issue.
> 
> Please read carefully:
> 
> To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.
> 
> To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

I claim this bounty

**Comment by Wilaz** [comment]
> Arbius has a $120 AIUS bounty for this issue!
> 
> Brief: Complete/fix issue.
> 
> Please read carefully:
> 
> To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.
> 
> To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

https://github.com/semperai/amica/pull/84
0x60064c964a2f908ddad7a5134aea2be4f30d56c2

**Comment by Wilaz** [comment]
> Arbius has a $120 AIUS bounty for this issue!
> 
> Brief: Complete/fix issue.
> 
> Please read carefully:
> 
> To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.
> 
> To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

https://github.com/semperai/amica/pull/84
0x58A2050A9EF6D2784F3b68285edE84D55313f3f8

**Comment by Wilaz** [comment]
https://github.com/semperai/amica/pull/84
0x58A2050A9EF6D2784F3b68285edE84D55313f3f8

**Comment by slowsynapse** [comment]
Cool, saw this, checking, under review.

**Comment by slowsynapse** [comment]
Thanks. Merged. Bounty sent at : https://etherscan.io/tx/0x55715e1dc5a1e3979db04422b4320362a9e02a854f3a8180b7262bc65a6cf3b0
