### ISSUE TITLE
share function should work with loaded characters from vrm

### ISSUE THREAD

**Issue by kasumi-1** [semperai/amica#69]
if you load a vrm file then go to share, the vrm file you previously selected is not preloaded to the vrm uploader widget. with share being a separate page this is tricker, this probably requires #56

**Comment by slowsynapse** [comment]
Arbius has a $100 AIUS bounty for this issue!

Brief: Share function should work with loaded characters from VRM.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by slowsynapse** [comment]
I believe this has been solved with char load and save. If problem happens again, should create new issue with bug label.
