### ISSUE TITLE
add RVC support for changing the voice from tts

### ISSUE THREAD

**Issue by aziib** [semperai/amica#71]
i like using xtts, but it's very slow compare to normal tts like ljspeech or speechT5. can you add RVC support where i can put my rvc model in any tts so the tts voice will change to my rvc model voice. similar like sillytavern rvc extension convert the output tts voice into rvc first and then show the message and play the output tts after the voice is changed. 
https://github.com/SillyTavern/SillyTavern-Extras
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

**Comment by slowsynapse** [comment]
Arbius has a $100 AIUS bounty for this issue!

Brief: Add RVC Support as outlined.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by Eidenz** [comment]
Hm, I got a few ideas to implement that. Won't take the bounty don't need it, I just want it as well and have the resources so I will have a look.

**Comment by Eidenz** [comment]
RVC has very poor API support, difficult to add to this project. I'm thinking of using a fork of RVC with an integrated FastAPI
https://github.com/SocAIty/Retrieval-based-Voice-Conversion-FastAPI

Will do my tests on this one from now on, as on top of providing a functioning API it allows sending binary directly, useful in our case.

**Comment by flukexp** [comment]
[#97 ](https://github.com/semperai/amica/pull/97)

**Comment by Eidenz** [comment]
Yup good job, better than the TTS-RVC-API I was checking in the end as it lacks rmvpe, which is the best-sounding one with small GPU usage.

**Comment by slowsynapse** [comment]
Thanks for the help @Eidenz

**Comment by slowsynapse** [comment]
Done and bounty sent!
