### ISSUE TITLE
Navigation inconsistency "Wrong place? Go home"

### ISSUE THREAD

**Issue by Vorlent** [semperai/amica#79]
The debug console and the settings menu both have an "X" to go back but importing or creating a character does not. There are no tooltips on the main screen so a user has to figure out what the buttons do by clicking on them. Knowing how to exit a sub-menu is a basic task that should be as easy as possible.

I have hacked some screenshots together to show what it should look like:

![amicaX](https://github.com/semperai/amica/assets/13166716/66c638d7-1dea-4956-af10-310ceb7efcfe)

![amicaX2](https://github.com/semperai/amica/assets/13166716/1485b658-3d10-4eb5-b8a4-f93747714505)

**Comment by slowsynapse** [comment]
Good point, yeah should be exact same exit button for all config panels.

**Comment by slowsynapse** [comment]
Arbius has a $50 AIUS bounty for this issue!

Brief: Change "go home" button to X to exit menu button.

Please read carefully:

To begin work on a bounty, reply by saying “I claim this bounty” - you will have 48 hours to submit your PR before someone else may attempt to claim this bounty.

To complete the bounty, within 48 hours of claiming, reply with a link to your PR referencing this issue and an Ethereum address. You must comply with reviewers comments and have the PR merged to receive the bounty reward. Please be sure to focus on quality submissions to minimize the amount of time reviewers must take.

**Comment by flukexp** [comment]
I claim this bounty
[#101 ](https://github.com/semperai/amica/pull/101)

**Comment by slowsynapse** [comment]
Please send ETH Address. Thanks.

**Comment by slowsynapse** [comment]
Merged and fixed. Thank you!

**Comment by flukexp** [comment]
> Please send ETH Address. Thanks.

0xD44248b6Ab4B6580cd982A80D4B26dC7058264f2

**Comment by slowsynapse** [comment]
Done and bounty sent. Thanks!
